# POSTTEST 7 Pengenalan Tensorflow
# Nama  : ANDI NUR FADILAH
# NIM   : 2109106015
# Kelas : INFORMATIKA A 21

## Mengimport library yang akan digunakan

In [26]:
import tensorflow as tf

## Membuat sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor.

In [27]:
random_tensor = tf.random.normal([5, 5])
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-2.0386217 , -0.06832754,  0.4171738 , -1.290271  ,  0.07783908],
       [ 0.31360468,  0.8964008 , -0.865767  ,  1.6553125 ,  0.90515447],
       [-0.2164705 ,  0.6014769 , -0.06881501,  0.4637691 ,  0.341684  ],
       [-0.3653365 , -1.5226474 ,  1.4054253 ,  1.572772  ,  0.8497446 ],
       [ 1.7515571 , -0.3123043 ,  0.82441854,  1.2453004 ,  0.8408737 ]],
      dtype=float32)>

## Membuat sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor.

In [28]:
prime_tensor = tf.constant([2, 3, 5, 7, 11,
                            13, 17, 19, 23, 29,
                            31, 37, 41, 43, 47,
                            53, 59, 61, 67, 71,
                            73, 79, 83, 89, 97], shape=[5, 5], dtype=tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

## Menampilkan dimensi dari variable random_tensor dan prime_tensor.

### Dimensi variable random_tensor

In [29]:
dim_display_random = tf.constant(['random_tensor'], shape=[5,5])
dim_display_random.shape

TensorShape([5, 5])

In [30]:
tf.shape(dim_display_random)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5])>

### Dimensi variable prime_tensor

In [31]:
dim_display_prime = tf.constant(['prime_tensor'], shape=[5,5])
dim_display_prime.shape

TensorShape([5, 5])

In [32]:
tf.shape(dim_display_prime)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5])>

## Menampilkan hasil dari perhitungan aritmetika variable random_tensor dan prime_tensor (menggunakan minimal 5 operator).

### Operator Penjumlahan

In [33]:
random_tensor = tf.random.normal([5, 5])
prime_tensor  = tf.constant([2, 3, 5, 7, 11,
                            13, 17, 19, 23, 29,
                            31, 37, 41, 43, 47,
                            53, 59, 61, 67, 71,
                            73, 79, 83, 89, 97], shape=[5, 5], dtype=tf.float32)

print("HASIL PENJUMLAHAN DARI VARIABLE RANDOM_TENSOR dan PRIME_TENSOR")
tf.add(random_tensor, prime_tensor)

HASIL PENJUMLAHAN DARI VARIABLE RANDOM_TENSOR dan PRIME_TENSOR


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.8192044,  3.291679 ,  3.9197912,  5.9960093, 12.370775 ],
       [12.79041  , 18.335018 , 18.941368 , 22.293875 , 28.846476 ],
       [29.560883 , 36.42693  , 41.555653 , 42.33834  , 46.80367  ],
       [52.718746 , 59.944653 , 59.97648  , 66.795975 , 70.71641  ],
       [72.49378  , 80.16298  , 81.878654 , 87.51999  , 98.83058  ]],
      dtype=float32)>

### Operator Pengurangan

In [34]:
random_tensor = tf.random.normal([5, 5])
prime_tensor  = tf.constant([2, 3, 5, 7, 11,
                            13, 17, 19, 23, 29,
                            31, 37, 41, 43, 47,
                            53, 59, 61, 67, 71,
                            73, 79, 83, 89, 97], shape=[5, 5], dtype=tf.float32)

print("HASIL PENGURANGAN DARI VARIABLE RANDOM_TENSOR dan PRIME_TENSOR")
tf.subtract(random_tensor, prime_tensor)

HASIL PENGURANGAN DARI VARIABLE RANDOM_TENSOR dan PRIME_TENSOR


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -1.3639503,  -2.3780358,  -5.2719946,  -7.358206 , -10.627363 ],
       [-13.696223 , -17.152843 , -18.143295 , -23.749542 , -29.470978 ],
       [-30.687653 , -36.03062  , -40.732685 , -43.234684 , -44.940243 ],
       [-53.878136 , -58.92001  , -63.016956 , -66.78708  , -70.91571  ],
       [-74.50668  , -78.289185 , -84.80833  , -87.85768  , -95.8295   ]],
      dtype=float32)>

### Operator Perkalian

In [35]:
random_tensor = tf.random.normal([5, 5])
prime_tensor  = tf.constant([2, 3, 5, 7, 11,
                            13, 17, 19, 23, 29,
                            31, 37, 41, 43, 47,
                            53, 59, 61, 67, 71,
                            73, 79, 83, 89, 97], shape=[5, 5], dtype=tf.float32)

print("HASIL PERKALIAN DARI VARIABLE RANDOM_TENSOR dan PRIME_TENSOR")
tf.matmul(random_tensor, prime_tensor)

HASIL PERKALIAN DARI VARIABLE RANDOM_TENSOR dan PRIME_TENSOR


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  20.38182  ,   27.024212 ,   30.122532 ,   38.790512 ,
          49.2863   ],
       [   1.5969791,   -1.2231259,   -2.6157553,   -2.0131502,
          -1.3813748],
       [ -53.110653 ,  -60.87399  ,  -65.88853  ,  -72.103516 ,
         -81.3366   ],
       [ -87.146904 ,  -97.81394  , -102.28945  , -112.26136  ,
        -120.35686  ],
       [ 132.42656  ,  145.6005   ,  154.16835  ,  162.5904   ,
         175.2147   ]], dtype=float32)>

### Operator Pembagian

In [36]:
random_tensor = tf.random.normal([5, 5])
prime_tensor  = tf.constant([2, 3, 5, 7, 11,
                            13, 17, 19, 23, 29,
                            31, 37, 41, 43, 47,
                            53, 59, 61, 67, 71,
                            73, 79, 83, 89, 97], shape=[5, 5], dtype=tf.float32)

print("HASIL PEMBAGIAN DARI VARIABLE RANDOM_TENSOR dan PRIME_TENSOR")
tf.divide(random_tensor, prime_tensor)

HASIL PEMBAGIAN DARI VARIABLE RANDOM_TENSOR dan PRIME_TENSOR


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-9.8087448e-01,  4.3198964e-01, -4.5469084e-01,  1.3285799e-01,
        -9.3548782e-03],
       [ 2.5971698e-02, -3.5716087e-02,  7.6995783e-02, -7.2443582e-02,
         2.5698405e-02],
       [-1.6575288e-02, -4.2424690e-02, -9.5679853e-03, -2.3302441e-02,
         8.3172740e-03],
       [ 1.2178859e-02, -2.1850014e-02,  1.4819419e-02, -7.6245272e-04,
        -9.1004875e-03],
       [-7.1996604e-03,  1.9942392e-02, -1.0097850e-02,  1.2709318e-02,
         2.8857628e-03]], dtype=float32)>

### Operator Pangkat

In [37]:
random_tensor = tf.random.normal([5, 5])
prime_tensor  = tf.constant([2, 3, 5, 7, 11,
                            13, 17, 19, 23, 29,
                            31, 37, 41, 43, 47,
                            53, 59, 61, 67, 71,
                            73, 79, 83, 89, 97], shape=[5, 5], dtype=tf.float32)

print("HASIL PANGKAT DARI VARIABLE RANDOM_TENSOR dan PRIME_TENSOR")
tf.pow(random_tensor, prime_tensor)

HASIL PANGKAT DARI VARIABLE RANDOM_TENSOR dan PRIME_TENSOR


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.5173788e-02,  6.2961035e+00, -1.3543417e-01,  2.6608494e+01,
         6.6584850e-12],
       [-4.9438992e+00,  5.5260807e-17,  1.9788865e-11, -1.5470589e+01,
         4.1634662e-06],
       [ 2.7718198e-32,  0.0000000e+00, -7.5196348e-37, -2.9420662e+07,
        -5.3695728e+14],
       [-1.2243898e+18,  0.0000000e+00, -7.5545669e-20, -2.7533088e+04,
         1.1015405e-19],
       [ 0.0000000e+00,  0.0000000e+00,  4.3514004e-28, -2.7330840e+20,
         2.2096938e+08]], dtype=float32)>

## Menampilkan nilai maksimum dan minimum dari variable random_tensor.

### Nilai maksimum variable random_tensor

In [38]:
max_random_kolom_tensor = tf.argmax(random_tensor, axis = 0)
max_random_baris_tensor = tf.argmax(random_tensor, axis = 1)

print("LOKASI NILAI MAKSIMUM")
print("Berdasarkan Kolom", max_random_kolom_tensor)
print("Berdasarkan Baris", max_random_baris_tensor)

LOKASI NILAI MAKSIMUM
Berdasarkan Kolom tf.Tensor([2 0 4 0 4], shape=(5,), dtype=int64)
Berdasarkan Baris tf.Tensor([1 4 0 4 4], shape=(5,), dtype=int64)


### Nilai minimum variable random_tensor

In [39]:
min_random_kolom_tensor = tf.argmin(random_tensor, axis = 0)
min_random_baris_tensor = tf.argmin(random_tensor, axis = 1)

print("LOKASI NILAI MINIMUM")
print("Berdasarkan Kolom", min_random_kolom_tensor)
print("Berdasarkan Baris", min_random_baris_tensor)

LOKASI NILAI MINIMUM
Berdasarkan Kolom tf.Tensor([3 4 0 4 2], shape=(5,), dtype=int64)
Berdasarkan Baris tf.Tensor([2 0 4 0 3], shape=(5,), dtype=int64)


## Menampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [40]:
concat_random_prime = tf.concat([random_tensor, prime_tensor], axis = 0)
concat_random_prime

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[-1.2318193e-01,  1.8465339e+00, -6.7041796e-01,  1.5979910e+00,
         9.6370302e-02],
       [-1.1308109e+00,  1.1057873e-01,  2.7330887e-01, -1.1264650e+00,
         6.5232491e-01],
       [ 9.5945515e-02,  7.5444266e-02, -1.3150178e-01, -1.4917278e+00,
        -2.0577991e+00],
       [-2.1942267e+00,  9.7970650e-02, -4.8587888e-01, -1.1648406e+00,
         5.4073679e-01],
       [ 9.3394332e-02,  1.1814069e-02,  4.6810678e-01, -1.6967791e+00,
         1.2190571e+00],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  6.7000000e+01,
         7.1000000e+01],
       [ 7.3000000e+01,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
      

## Menampilkan hasil sorting dari variable random_tensor dan prime_tensor (descending)

### Hasil Sorting dari Variable Random Tensor

In [41]:
print("HASIL SORTING SECARA DESCENDING DARI VARIABLE RANDOM_TENSOR")
random_tensor_descending = tf.sort(random_tensor, direction = "DESCENDING")
random_tensor_descending

HASIL SORTING SECARA DESCENDING DARI VARIABLE RANDOM_TENSOR


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.8465339 ,  1.597991  ,  0.0963703 , -0.12318193, -0.67041796],
       [ 0.6523249 ,  0.27330887,  0.11057873, -1.126465  , -1.1308109 ],
       [ 0.09594551,  0.07544427, -0.13150178, -1.4917278 , -2.057799  ],
       [ 0.5407368 ,  0.09797065, -0.48587888, -1.1648406 , -2.1942267 ],
       [ 1.2190571 ,  0.46810678,  0.09339433,  0.01181407, -1.6967791 ]],
      dtype=float32)>

### Hasil Sorting dari Variable Prime Tensor

In [42]:
print("HASIL SORTING SECARA DESCENDING DARI VARIABLE PRIME_TENSOR")
prime_tensor_descending = tf.sort(prime_tensor, direction = "DESCENDING")
prime_tensor_descending

HASIL SORTING SECARA DESCENDING DARI VARIABLE PRIME_TENSOR


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]], dtype=float32)>